PR: 세션 로그인 관련
Young-Camper/BE pull request #16
Opened 2024-08-29 16:44 UTC by devbini

Spring security에 연결 된 세션 로그인 기능입니당

2024-09-01 10:38 UTC, seeun0210 requested changes
LGTM:) 수고하셨습니다! 
몇몇 수정해야 할 사항들이 보여서 코멘트달아두었어요! 

그리고 말씀드린 커스텀 쿠키는 
```
import org.springframework.boot.web.servlet.server.CookieSameSiteSupplier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.session.web.http.CookieHttpSessionIdResolver;
import org.springframework.session.web.http.HttpSessionIdResolver;
import org.springframework.session.web.http.DefaultCookieSerializer;

@Configuration
public class SessionConfig {

    @Bean
    public HttpSessionIdResolver httpSessionIdResolver() {
        CookieHttpSessionIdResolver resolver = new CookieHttpSessionIdResolver();
        DefaultCookieSerializer cookieSerializer = new DefaultCookieSerializer();
        
        cookieSerializer.setCookieName("YCAMPADMIN");  // 쿠키 이름 설정
        cookieSerializer.setUseHttpOnlyCookie(true);
        cookieSerializer.setSameSite("Lax");  // 또는 "Strict", "None" 으로 설정 가능
        cookieSerializer.setCookiePath("/");
        
        resolver.setCookieSerializer(cookieSerializer);
        return resolver;
    }
}
```
이렇게 가능한데 한번 해보시겠어요?

2024-09-01 10:38 UTC, seeun0210 commented on src/main/java/com/youngcamp/server/controller/ExampleController.java
> +  }
```suggestion
  public Boolean AdminCheckControl(){
   return adminChecker.isAdmin();
  }
```
string보다는 boolean이 더 명확할 것 같은데 이렇게 수정해보는 건 어떨까요?

2024-09-01 10:38 UTC, seeun0210 commented on src/main/java/com/youngcamp/server/config/SecurityConfig.java
> +                    .authenticated()
/api/admin/**에 대해서 admin만 가능하게 하려고 의도하신 거라면 
```suggestion
 .requestMatchers("/api/admin/**")
                    .hasRole("ADMIN") 
```
이렇게 수정되어야 해요.

2024-09-01 13:15 UTC, devbini commented on src/main/java/com/youngcamp/server/controller/ExampleController.java
> +  }
이거는 너무 좋습니다 !
좀 더 간결하고 좋을 것 같네요!! 👍 

바로 적용 해 두겠습니다!

2024-09-01 13:17 UTC, devbini commented on src/main/java/com/youngcamp/server/config/SecurityConfig.java
> +                    .authenticated()
어차피 로그인할 수 있는 계정이란 게 Admin밖에 없어서
로그인이 된 사용자 == 관리자 로 인식하고 저렇게 설정을 했었던 것 같네요.

바로 위에 DEV는 hasRole로 잡아줬으니
일관성을 위해서 바꿔주는 게 가독성적으로 좋을 것 같습니다! 👍 
이거로 바꿔 낄게요!

2024-09-01 13:58 UTC, devbini commented
원래 세션 설정으로만 마무리하려 했는데,
XSS 방지 및 보안 설정 등 말씀 주신 커스텀 쿠키가 좋을 것 같습니다!
.yml로는 한계가 있네요ㅠㅠㅠ...

리뷰 감사합니다!
신규 코드 확인 부탁드릴게요~~!

2024-09-01 23:16 UTC, devbini commented
> LGTM:) 수고하셨습니다! 몇몇 수정해야 할 사항들이 보여서 코멘트달아두었어요!
> 
> 그리고 말씀드린 커스텀 쿠키는
> 
> ```
> import org.springframework.boot.web.servlet.server.CookieSameSiteSupplier;
> import org.springframework.context.annotation.Bean;
> import org.springframework.context.annotation.Configuration;
> import org.springframework.session.web.http.CookieHttpSessionIdResolver;
> import org.springframework.session.web.http.HttpSessionIdResolver;
> import org.springframework.session.web.http.DefaultCookieSerializer;
> 
> @Configuration
> public class SessionConfig {
> 
>     @Bean
>     public HttpSessionIdResolver httpSessionIdResolver() {
>         CookieHttpSessionIdResolver resolver = new CookieHttpSessionIdResolver();
>         DefaultCookieSerializer cookieSerializer = new DefaultCookieSerializer();
>         
>         cookieSerializer.setCookieName("YCAMPADMIN");  // 쿠키 이름 설정
>         cookieSerializer.setUseHttpOnlyCookie(true);
>         cookieSerializer.setSameSite("Lax");  // 또는 "Strict", "None" 으로 설정 가능
>         cookieSerializer.setCookiePath("/");
>         
>         resolver.setCookieSerializer(cookieSerializer);
>         return resolver;
>     }
> }
> ```
> 
> 이렇게 가능한데 한번 해보시겠어요?

감사합니다~!
원래는 세션 설정으로 마무리하고, 쿠키는 .yml에서 생성하는거로만 관리하려 헀는데
XSS 공격이나 여러 보안적으로 커스텀 쿠키가 꼭 필요할 것 같네요ㅠㅠ

`CookieConfig `클래스를 만들어 넣어놨습니다!
확인 부탁드릴게요 👍

2024-09-02 01:04 UTC, Juhyeok0202 approved these changes
저도 뭔가 코멘트를 남기고 싶어서 열심히 봤는데 못찾겠네요 🥹 코드가 술술 읽혀요😊‼️ 
수고 많으셨습니다!

2024-09-02 01:30 UTC, seeun0210 approved these changes

2024-09-02 01:43 UTC, merged